// <auto-generated />
using System;
using EFCore.Demo.Db;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EFCore.Demo.Migrations
{
    [DbContext(typeof(DemoContext))]
    [Migration("20201204143824_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseIdentityColumns()
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.0");

            modelBuilder.Entity("Companies.Demo.Entities.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("Companies.Demo.Entities.Company", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("Companies.Demo.Entities.ConsultantProject", b =>
                {
                    b.Property<Guid>("ConsultantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConsultantId", "ProjectId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ConsultantProjects");
                });

            modelBuilder.Entity("Companies.Demo.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Employee");
                });

            modelBuilder.Entity("Companies.Demo.Entities.Project", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("ClientId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("ClientId1");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Companies.Demo.Entities.Consultant", b =>
                {
                    b.HasBaseType("Companies.Demo.Entities.Employee");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CompanyId1")
                        .HasColumnType("uniqueidentifier");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId1");

                    b.HasDiscriminator().HasValue("Consultant");
                });

            modelBuilder.Entity("Companies.Demo.Entities.StaffMember", b =>
                {
                    b.HasBaseType("Companies.Demo.Entities.Employee");

                    b.Property<Guid?>("CompanyId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StaffMember_CompanyId");

                    b.Property<Guid?>("CompanyId1")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("StaffMember_CompanyId1");

                    b.Property<int>("Pole")
                        .HasColumnType("int");

                    b.HasIndex("CompanyId");

                    b.HasIndex("CompanyId1");

                    b.HasDiscriminator().HasValue("StaffMember");
                });

            modelBuilder.Entity("Companies.Demo.Entities.ConsultantProject", b =>
                {
                    b.HasOne("Companies.Demo.Entities.Consultant", null)
                        .WithMany("ConsultantProjects")
                        .HasForeignKey("ConsultantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Companies.Demo.Entities.Project", null)
                        .WithMany("ConsultantProjects")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Companies.Demo.Entities.Project", b =>
                {
                    b.HasOne("Companies.Demo.Entities.Client", "Client")
                        .WithMany("Projects")
                        .HasForeignKey("ClientId");

                    b.HasOne("Companies.Demo.Entities.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId1")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Client");
                });

            modelBuilder.Entity("Companies.Demo.Entities.Consultant", b =>
                {
                    b.HasOne("Companies.Demo.Entities.Company", "Company")
                        .WithMany("Consultants")
                        .HasForeignKey("CompanyId");

                    b.HasOne("Companies.Demo.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId1")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Companies.Demo.Entities.StaffMember", b =>
                {
                    b.HasOne("Companies.Demo.Entities.Company", "Company")
                        .WithMany("StaffMembers")
                        .HasForeignKey("CompanyId");

                    b.HasOne("Companies.Demo.Entities.Company", null)
                        .WithMany()
                        .HasForeignKey("CompanyId1")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Company");
                });

            modelBuilder.Entity("Companies.Demo.Entities.Client", b =>
                {
                    b.Navigation("Projects");
                });

            modelBuilder.Entity("Companies.Demo.Entities.Company", b =>
                {
                    b.Navigation("Consultants");

                    b.Navigation("StaffMembers");
                });

            modelBuilder.Entity("Companies.Demo.Entities.Project", b =>
                {
                    b.Navigation("ConsultantProjects");
                });

            modelBuilder.Entity("Companies.Demo.Entities.Consultant", b =>
                {
                    b.Navigation("ConsultantProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
